language: rust
rust: nightly

os: linux
dist: bionic

env:
  global:
  - RUST_BACKTRACE=full
  - CODECOV_DIR=${HOME}/.cache/tools/codecov

matrix:
  include:
  - env: MAKE_TARGET=coverage
  - env: MAKE_TARGET=doc
  - env: MAKE_TARGET=lint
    # Before updating this make sure that nighly-YYYY-MM-DD contains either rustfmt and clippy
    # Use
    #   * `curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/clippy`
    #   * `curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/rustfmt`
    # to validate that both tools are available
    rust: nightly-2020-04-10

install:
- bash scripts/travis/install.sh

before_script:
- bash scripts/travis/before_script.sh

script:
- make "${MAKE_TARGET}"

# cache:
#   timeout: 3600
#   directories:
#   - ${HOME}/.cache/pre-commit
#   - ${CODECOV_DIR}
#   - ${HOME}/.cargo/
#   - ${TRAVIS_BUILD_DIR}/target

# notifications:
#   email: false
#   slack:
#     # Personal Slack notification
#     secure: Something not set yet

deploy:
  provider: cargo
  token:
    secure: Lcoai+pKEV0rtFl9WeExN7AY+Du0thd0jSioNoH8kGXCPo4zQLAVmCpivI3v5OmBf+jydQTMsr4TjHYXtTIpWknEbGMcxyjSxBsuaGxTW/Wvh9ZkFPyFCaWX3DOtnCZ4oK3gdri7Ise13ajZokAcO7GaAuMzXKbrAPqDTSWrzopiQ6pd+gCbIhTIlSwfDUQnNL97zH4WeMb4x/umQRsOAsRe7CdXDeNq3C5xhWXZADu7q2GCA4jHmEDsqLTvF6guvr23kpheAIlN1rdbsfb1lJbDbFnmMcFRoqUxrsbpLONLJidUSWte2KiFkPNSn6kEjZ64texA0LqHqYBo1wHK9ksSW9LmUElMwQaCbVVmSpD24wG9VUT7ioEkPa4fphN/BRWqwdqMNkB5NPPPqHXimOw+MMa7AkU+4Grh14BR1GQEiN3zML+Ivt0dq69QGpe01S3v0VwXbOTsRGx/XrtT7o/UH4hB64LTbfdN5bjLOG80sazOxZSS2rCdsBJP8/Ue1CgQ0gJrsQ4C3bMSc1El1WOYctl22/v6jY/TtT89uGThWQEx+v8nMssQFJU3tfEpkMbuUVuoFKc3xE5hB7BsJXDcXjdg6to3UFuLssGAOvJ6ImAsxvStKbT2pVUHCJJYqZ/DLP+8UoMFmT+dJbwoS8SwiFZtmdvgxso2oxlnDac=
  on:
    condition: ${TRAVIS_REPO_SLUG} = macisamuele/loader-rs && ${MAKE_TARGET} = coverage && $(bash scripts/cargo-version.sh) = ${TRAVIS_TAG}
    tags: true
