language: rust
rust: stable

env:
  global:
  - RUST_BACKTRACE=full
  - CODECOV_DIR=${HOME}/.cache/tools/codecov

matrix:
  include:
  # TODO: add osx and windows testing environments
  - os: linux
    dist: xenial
    env: MAKE_TARGET=coverage
    rust: nightly
  - os: linux
    dist: xenial
    env: MAKE_TARGET=test
  - os: linux
    dist: xenial
    env: MAKE_TARGET=doc
  - os: linux
    dist: xenial
    env: MAKE_TARGET=lint
  allow_failures:
  - env: MAKE_TARGET=lint

install:
- bash scripts/travis/install.sh

before_script:
- bash scripts/travis/before_script.sh

script:
- make "${MAKE_TARGET}"

cache:
  timeout: 3600
  directories:
  - ${HOME}/.cache/pre-commit
  - ${CODECOV_DIR}
  - ${HOME}/.cargo/
  - ${TRAVIS_BUILD_DIR}/target

# notifications:
#   email: false
#   slack:
#     # Personal Slack notification
#     secure: Something not set yet

deploy:
  provider: cargo
  token:
    secure: a7uM0rXpBTpUGBYYQAbSmwR42VWgCz3hpmjU6OPW2GPhbVWMh0re+ya/mef+qbmM2p8XGIXK0LU7L9rRipiZ+7V2HUyIf4Dfss4ALauhIe493hUUYmvjoj5TL2kmcs+pQV0dzIOehBaJzOQ0Xx+iro/0wn03b6DdV4Fg5EarPcCZLS+PTzUWrJSERCic7NJ0i+KGs0t8NaMH+aNUhUS1s2XNYVHZUnPkmVfW0++kdr0nyrMbYSayJykvsc+DYxAbTbylvG70s7ngtkbErVvEHH+EskWbwxEM7tNZV2P/hYKVH+roldZWfzg/vQ621ztiLrEZJvzHKn6Y/DmUNmCnfxiZrEBHecZ62un7RNoeyEwDa9UK7sBoxOt5zWXxU82dtQb0tMBsklMshxQpvgbuguZ2TQL5FsYF5A9HzGR57J0saw2v5faFm0WhBktpAPxdFY/2MUIvI8DQMukIu+FR47xayD01oqHozS/Dr1RwhBKMw4sikjwd0JNWroPM5JxJByxnD++ezUdYsZmhw+qm/x8PXrjtSX9VS5O+hOAdNXfQRGW86kYrok957jsP/xzpCtADKNEh2hM/QgOFa9hiuB/9Hptmb5yYVQ6y4Xr10WGGie0FI9La5NGXbCR40caFk4qx0X7lF+Pgp2wcbLXOUSX9xCiRwjJwoGVHUoiYmn0=
  on:
    condition: ${TRAVIS_REPO_SLUG} = macisamuele/loader-rs && ${MAKE_TARGET} = test && $(bash scripts/cargo-version.sh) = ${TRAVIS_TAG}
    tags: true
